### ISSUE TITLE
Where can I get re-id pt files ?

### ISSUE THREAD

**Issue by moonsh** [mikel-brostrom/Yolov7_StrongSORT_OSNet#1]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Thank you for sharing your work.
It said I need to download re-id pt files in the description but all the pretrained models in zoo are pth files.

for example, 
osnet_x0_25_market1501.pt

**Comment by mikel-brostrom** [comment]
Just rename the weights and set the path for the strong-sort-weigths accordingly

**Comment by moonsh** [comment]
Thank you !
