### ISSUE TITLE
Multi-Camera

### ISSUE THREAD

**Issue by mingchih1126** [mikel-brostrom/Yolov7_StrongSORT_OSNet#10]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

How to use Multi-Camera to track pedestrians?  
I read the code and didn't find this part！

**Comment by mikel-brostrom** [comment]
create a txt file with the streams to track then pass it to the tracker

`python track.py --source sources.txt`

**Comment by sparshgarg23** [comment]
@mikel-brostrom  could you please elaborate on how the sources.txt 's format is.
i am assuming by streams you are referring to the object being viewed from different cameras?

**Comment by mikel-brostrom** [comment]
It should contain your sources on separate lines. An example:

```
https://www.youtube.com/watch?v=FNTHBcHmrIg
https://www.youtube.com/watch?v=WwheIKQGz8U
```

**Comment by Hemilibeatriz** [comment]
When I do it this way, the two windows that open are black and I have the "No detections" return in the console. In other words, the variable "det" is None and its len is empty. What may be the problem? I tested with local videos and the two links mentioned in this issue.
