### ISSUE TITLE
mc_lambda is hard coded?

### ISSUE THREAD

**Issue by solkien** [mikel-brostrom/Yolov7_StrongSORT_OSNet#11]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I can't find where mc_lambda from the configuration file is used. Shouldn't it be passed to calculate the cost matrix in the gate_cost_matrix function?
https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/blob/701f93b1eb303d4eca431e1719473a0ce2826a26/strong_sort/sort/linear_assignment.py#L173

**Comment by wsw321** [comment]
It seems hard coded.
