### ISSUE TITLE
"save_one_box" not defined

### ISSUE THREAD

**Issue by lorenzlorg** [mikel-brostrom/Yolov7_StrongSORT_OSNet#13]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov7_StrongSORT_OSNet Component

Other

### Bug

Unresolved reference 'save_one_box'

**Comment by QingyuanLiu0** [comment]
I have the similar question

**Comment by Hemilibeatriz** [comment]
I have the same, any way to fix?
