### ISSUE TITLE
I would like to speed up StrongSort

### ISSUE THREAD

**Issue by getarobo** [mikel-brostrom/Yolov7_StrongSORT_OSNet#17]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, greatly appreciated for yolov7 MOT!

I would like to run this in real-time and was hoping if there were some ways to speed up the sort.

Yolo takes around (0.007s) and StrongSort(0.005s~0.06s)(1person~12person)

Is there like a variables I can play with ?

Thanks!

**Comment by mikel-brostrom** [comment]
If you have exported the models to the fastest framework running on your desired hardware I would say there is very little more to do more than changing tracking module. You may find OCSORT interesting:
https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/tree/ocsort. I achieved 700FPS on CPU with this tracking module
