### ISSUE TITLE
Pose model

### ISSUE THREAD

**Issue by mukeshnarendran7** [mikel-brostrom/Yolov7_StrongSORT_OSNet#18]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Great work in the repository. I have managed to add yolov7 model with my Pose model but i want to track the object too. What would be the best way to do it using your work? Thanks

Yolov7 (bbox detection) -> Sort labels -> Pose predictor (on bbox from frames (already done)) -> Merge all of them together in a video

**Comment by mikel-brostrom** [comment]
You could pass both the bboxes and pose information to:

https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/blob/4cf9555609ae2c6c9a9dba7f4202e0a509ef90b5/track.py#L209

And store the pose associated to as specific bbox in the track.

**Comment by mukeshnarendran7** [comment]
Hey mikel, thanks for getting back. I got it to work in a way but am not sure its the same as you mentioned.
So what i did was:
- Get the yolo predictions sorted out from your code with the ids
- Passed it onto Pose model where it does keypoint detection on multiple objects
- Returns object with keypoint/Pose predictions and id.
Can i add temporal tracking of the keypoints solely?
