### ISSUE TITLE
OCSORT for Yolov7

### ISSUE THREAD

**Issue by uberlumi** [mikel-brostrom/Yolov7_StrongSORT_OSNet#20]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Good day,
We are running it on livefeed such as Youtube or public city cams.
Improvement for Yolov7 (from Yolov5) is noticeable from 120ms to 20ms. 
You did prepare Yolov5 to work with OCSORT, will you do it for Yolov7?
Do you have an ETA?
Thanks Bunches,
O

**Comment by mikel-brostrom** [comment]
I would like to unify everything in a singe repo. Yolov5,v6,v7 with trackers and call it something like yolo_track. I just don't have the time atm
