### ISSUE TITLE
Yolov7 stops detecting after a period of time

### ISSUE THREAD

**Issue by uberlumi** [mikel-brostrom/Yolov7_StrongSORT_OSNet#21]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Good day,
We've been running it CPU version and GPU version, and Yolov7 did stop detecting after a period of time from 2h30 to 6h40...
And it did not recover.
Any clue?

Thanks for your help guys.
O

**Comment by uberlumi** [comment]
It is exactly after 6 hours.
same with CPU and GPU.

**Comment by mikel-brostrom** [comment]
Interesting. I have never tracked for so long. What crashes exactly? Out of memory?
