### ISSUE TITLE
Cross Camera for same ID

### ISSUE THREAD

**Issue by kjfjsd99** [mikel-brostrom/Yolov7_StrongSORT_OSNet#25]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi, thanks for your work! It is a great code for me to learn new things. And I just want to ask if this code can be used for tracking a person with different cameras? For example, if a person is detected by a camera, then this person is labeled with an id number, then this person can keep this id number to the other camera. 

Thanks~

**Comment by JohnTrunix** [comment]
Hi @kjfjsd99, did you manage to solve your question?
