### ISSUE TITLE
Does StrongSORT fit more person tracking objectives?

### ISSUE THREAD

**Issue by ar4development** [mikel-brostrom/Yolov7_StrongSORT_OSNet#26]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,

Despite vehicle seem to be tracked indeed, it looks like existing pre-trained models are trained specifically for person re-identification. Does it mean the main purpose of StrongSORT is person re-identification or I just have to train the model over my own dataset to improve tracking of vehicles?

**Comment by mikel-brostrom** [comment]
Training models on your specific scenario is always good practice for achieving the best possible results. The ReID models provided in this repo will work best for the task of people re-identification as they are trained for this purpose.

**Comment by SunnyGrocery** [comment]
> Training models on your specific scenario is always good practice for achieving the best possible results. The ReID models provided in this repo will work best for the task of people re-identification as they are trained for this purpose.

Have these YOLOv7 models been re-parameterized?
