### ISSUE TITLE
Enhancements 

### ISSUE THREAD

**Issue by ozayr** [mikel-brostrom/Yolov7_StrongSORT_OSNet#27]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi Mikel, I see your yolov5 repo is getting a lot of attention and updates, I was just wondering will the updates make its way to this repo? especially since the standard performance of yolov7 seems to be better than v5. Thanks for the work and effort extremely informative and helpful.

**Comment by mikel-brostrom** [comment]
I would like to but I sadly don't have time to update two repos...
