### ISSUE TITLE
integration with ROS for real-time tracking

### ISSUE THREAD

**Issue by PardisTaghavi** [mikel-brostrom/Yolov7_StrongSORT_OSNet#30]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Feel free to check it out for integration of the code with ROS :

https://github.com/PardisTaghavi/yolov7_strongsort_ros.git

**Comment by mikel-brostrom** [comment]
Nice @PardisTaghavi ! I am not so familiar with ROS but if you have any application video feel free to share it here :smile:

**Comment by PardisTaghavi** [comment]
I just added a demo video on the readme file and here is the link.
(https://user-images.githubusercontent.com/98438319/205487635-836155cf-2288-40a1-a02f-8e730c787520.gif)
thank you for your feedback and hope this would help.
