### ISSUE TITLE
StrongSORT_OSNet gives different ID for the same person

### ISSUE THREAD

**Issue by Ishihara-Masabumi** [mikel-brostrom/Yolov7_StrongSORT_OSNet#33]
I tried to run Yolov7_StrongSORT_OSNet using --source TownCenter.mp4.
Then, after passersby pass each other, the hidden one has a different ID, like below.

![before](https://user-images.githubusercontent.com/23301778/207214248-09ddbb9a-97d8-40a0-b347-68ee38d0f8b2.jpg)
　　　　　　　　　　　　　　　　　　　　　　　　　　　　↓
![after](https://user-images.githubusercontent.com/23301778/207214276-26cd3da2-ec37-48a8-a585-dbc6ef1ddaea.jpg)

Please fix it.

**Comment by mikel-brostrom** [comment]
This is not a solved research area. I recommend you to train a model on people only. That will give much better results
