### ISSUE TITLE
Is there any C++ implemention?

### ISSUE THREAD

**Issue by mvpzhangqiu** [mikel-brostrom/Yolov7_StrongSORT_OSNet#35]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Is there any C++ implemention?

**Comment by mikel-brostrom** [comment]
Not what I know
