### ISSUE TITLE
NMS preprocessing not working properly

### ISSUE THREAD

**Issue by debasishaimonk** [mikel-brostrom/Yolov7_StrongSORT_OSNet#36]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

The nms preprocessing which is present in the sort folder, when i applied in the strongsort.py, in the update function, it seems like it is not performing properly. even in the outside where is there nms in the track.py script, it is also not performing well. Could please help me this, what been happening with this?

**Comment by mikel-brostrom** [comment]
https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/blob/701f93b1eb303d4eca431e1719473a0ce2826a26/strong_sort/sort/preprocessing.py#L6

is not used at all and should be deleted

**Comment by debasishaimonk** [comment]
but even the nms present in the track.py, which is being used, seems like it's not giving the proper result. It is using the yolov7 module's nms preporcessing which is present in the general.py script.

**Comment by mikel-brostrom** [comment]
> it seems like it is not performing properly

You are not giving any information at all about the issue so I cannot help you out.
What is not performing properly?
