### ISSUE TITLE
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by AT9991** [mikel-brostrom/Yolov7_StrongSORT_OSNet#38]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov7_StrongSORT_OSNet Component

Tracking

### Bug

Hi, I have seen #2 having the same issue, I tried incorporating the changes mentioned in the comments, but the issue persists. Two days ago this problem was not there. But when I cloned the repo today, this issue came up again. Please help me in solving it. 

video 1/1 (1/494) /content/Yolov7_StrongSORT_OSNet/Dec27_TestVideo.mp4: Traceback (most recent call last):
  File "track.py", line 332, in <module>
    main(opt)
  File "track.py", line 327, in main
    run(**vars(opt))
  File "/usr/local/lib/python3.8/dist-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 149, in run
    for frame_idx, (path, im, im0s, vid_cap) in enumerate(dataset):
  File "/content/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 189, in __next__
    img = letterbox(img0, self.img_size, stride=self.stride)[0]
  File "/content/Yolov7_StrongSORT_OSNet/yolov7/utils/datasets.py", line 998, in letterbox
    dw, dh = np.mod(dw, stride), np.mod(dh, stride)  # wh padding
  File "/usr/local/lib/python3.8/dist-packages/torch/_tensor.py", line 955, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### Environment

Google Colab

**Comment by liuliaocheng** [comment]
I have the same problem

**Comment by DonghanChen** [comment]
I have the same problem

**Comment by chaohuichen1024** [comment]
I have the same problem too

**Comment by chaohuichen1024** [comment]
@AT9991 
If you want to change the data in CUDA tensor format to numpy, you need to convert it to cpu float-tensor first and then to numpy format. Numpy cannot read CUDA Tensor. It needs to be converted to CPU Tensor
resolvent
Change the error code self. numpy() to self. cpu(). numpy()
