### ISSUE TITLE
ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by world2025** [mikel-brostrom/Yolov7_StrongSORT_OSNet#4]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

Traceback (most recent call last):
  File "track.py", line 38, in <module>
    from strong_sort.utils.parser import get_config
  File "/app/Yolov7_StrongSORT_OSNet/strong_sort/__init__.py", line 1, in <module>
    from .strong_sort import StrongSORT
  File "/app/Yolov7_StrongSORT_OSNet/strong_sort/strong_sort.py", line 9, in <module>
    from .sort.nn_matching import NearestNeighborDistanceMetric
  File "/app/Yolov7_StrongSORT_OSNet/strong_sort/sort/nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix

### Minimal Reproducible Example

from torchreid.metrics.distance import compute_distance_matrix

**Comment by xugaoxiang** [comment]
Get the code by

`
git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet.git
`

**Comment by world2025** [comment]
ok

**Comment by Shawn7702** [comment]
I have the same bug. I got the right code.
**Environment:**
Colab, Customer Dataset, Improved yolov7.pt

Traceback (most recent call last):
  File "/content/Yolov7_StrongSORT_OSNet/track.py", line 38, in <module>
    from strong_sort.utils.parser import get_config
  File "/content/Yolov7_StrongSORT_OSNet/strong_sort/__init__.py", line 1, in <module>
    from .strong_sort import StrongSORT
  File "/content/Yolov7_StrongSORT_OSNet/strong_sort/strong_sort.py", line 9, in <module>
    from .sort.nn_matching import NearestNeighborDistanceMetric
  File "/content/Yolov7_StrongSORT_OSNet/strong_sort/sort/nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid'**

**Comment by alexkutsan** [comment]
I have a similar issue. I am trying to use this repo as a module with import.  

```
developer@5401b999b93e:~$ git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet.git 
Cloning into 'Yolov7_StrongSORT_OSNet'...
remote: Enumerating objects: 1655, done.
remote: Counting objects: 100% (93/93), done.
remote: Compressing objects: 100% (51/51), done.
remote: Total 1655 (delta 46), reused 84 (delta 42), pack-reused 1562
Receiving objects: 100% (1655/1655), 36.04 MiB | 2.84 MiB/s, done.
Resolving deltas: 100% (834/834), done.
Submodule 'strong_sort/deep/reid' (https://github.com/KaiyangZhou/deep-person-reid) registered for path 'strong_sort/deep/reid'
Submodule 'yolov7' (https://github.com/mikel-brostrom/yolov7) registered for path 'yolov7'
Cloning into '/home/developer/Yolov7_StrongSORT_OSNet/strong_sort/deep/reid'...
remote: Enumerating objects: 9860, done.        
remote: Counting objects: 100% (10/10), done.        
remote: Compressing objects: 100% (9/9), done.        
remote: Total 9860 (delta 1), reused 10 (delta 1), pack-reused 9850        
Receiving objects: 100% (9860/9860), 9.57 MiB | 5.07 MiB/s, done.
Resolving deltas: 100% (7286/7286), done.
Cloning into '/home/developer/Yolov7_StrongSORT_OSNet/yolov7'...
remote: Enumerating objects: 500, done.        
remote: Total 500 (delta 0), reused 0 (delta 0), pack-reused 500        
Receiving objects: 100% (500/500), 32.76 MiB | 3.95 MiB/s, done.
Resolving deltas: 100% (260/260), done.
Submodule path 'strong_sort/deep/reid': checked out '4a0793780bd13f53ec2ca753a94dcef62dc9e955'
Submodule path 'yolov7': checked out '60978d6acd409cb8089d44813659ced59d41aa96'

developer@5401b999b93e:~$ python3 -m pip install -r ./Yolov7_StrongSORT_OSNet/requirements.txt 
...
developer@5401b999b93e:~$ python3
Python 3.8.10 (default, Jun 22 2022, 20:18:18) 
[GCC 9.4.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> 
>>> import sys
>>> sys.path.insert(1, './Yolov7_StrongSORT_OSNet')
>>> import track
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/developer/./Yolov7_StrongSORT_OSNet/track.py", line 38, in <module>
    from strong_sort.utils.parser import get_config
  File "/home/developer/./Yolov7_StrongSORT_OSNet/strong_sort/__init__.py", line 1, in <module>
    from .strong_sort import StrongSORT
  File "/home/developer/./Yolov7_StrongSORT_OSNet/strong_sort/strong_sort.py", line 9, in <module>
    from .sort.nn_matching import NearestNeighborDistanceMetric
  File "/home/developer/./Yolov7_StrongSORT_OSNet/strong_sort/sort/nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid'


``` 

What am i doing wrong?

**Comment by alexkutsan** [comment]
Found an ugly workaround: 

```
import os
import sys
from pathlib import Path
FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]  # yolov5 strongsort root directory
sys.path.append(str(ROOT / 'Yolov7_StrongSORT_OSNet'))  # add yolov5 ROOT to PATH

os.chdir('./Yolov7_StrongSORT_OSNet')
import track
os.chdir('../')

```
