### ISSUE TITLE
Error of yolov7 module not found when file is there

### ISSUE THREAD

**Issue by adelinawong** [mikel-brostrom/Yolov7_StrongSORT_OSNet#40]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

Traceback (most recent call last):
  File "track.py", line 32, in <module>
    from yolov7.models.experimental import attempt_load
ModuleNotFoundError: No module named 'yolov7'

Would like to know why I am facing this error when i have yolov7 in the same folder as track.py? Thank you and hope to hear from u soon!

**Comment by mikel-brostrom** [comment]
You have not cloned the repo correctly. Double check the readme
