### ISSUE TITLE
IndexError when using multi-camera to track

### ISSUE THREAD

**Issue by Lithium100** [mikel-brostrom/Yolov7_StrongSORT_OSNet#41]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

Traceback (most recent call last):
  File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 332, in <module>
    main(opt)
  File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 327, in main
    run(**vars(opt))
  File "D:\Software\Anaconda3\envs\y7ss\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 191, in run
    curr_frames[i] = im0
IndexError: list assignment index out of range

I want to use the local video,  and I use the format mentioned in #10 
D:/Projects/yolov7/Yolov7_StrongSORT_OSNet/data/back.mp4
D:/Projects/yolov7/Yolov7_StrongSORT_OSNet/data/front.mp4

### Environment

OS:Windows 11

**Comment by quintonx1211** [comment]
> 
Have you solved your problem? I encountered the same error. Pls respond if you have solutions. Tks.

**Comment by rlekey** [comment]
on line 114 in track.py, replacy nr_sources = 1 with nr_sources = len(dataset.sources)

**Comment by rlekey** [comment]
I made a pr with this fix https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/pull/52

**Comment by JDmoric** [comment]
> on line 114 in track.py, replacy nr_sources = 1 with nr_sources = len(dataset.sources)

Dear Author，

I tried your solution that revise nr_sources = len(dataset.sources), but the error still exits :
"curr_frames[i] = im0
IndexError: list assignment index out of range"

Look forward your further solution. If the problem is not easy to deal with, the business inquiry is also accepted.

Best wishes

**Comment by JDmoric** [comment]
> ### Search before asking
> * [x]  I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.
> 
> ### Yolov7_StrongSORT_OSNet Component
> _No response_
> 
> ### Bug
> Traceback (most recent call last): File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 332, in main(opt) File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 327, in main run(**vars(opt)) File "D:\Software\Anaconda3\envs\y7ss\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context return func(*args, **kwargs) File "D:\Projects\yolov7\Yolov7_StrongSORT_OSNet\track.py", line 191, in run curr_frames[i] = im0 IndexError: list assignment index out of range
> 
> I want to use the local video, and I use the format mentioned in #10 D:/Projects/yolov7/Yolov7_StrongSORT_OSNet/data/back.mp4 D:/Projects/yolov7/Yolov7_StrongSORT_OSNet/data/front.mp4
> 
> ### Environment
> OS:Windows 11
> 
> ### Minimal Reproducible Example
> _No response_

Hi, Mr Lithium
Have you solved this issue? I meet the same bug hhh.
