### ISSUE TITLE
no support for cuda? can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

### ISSUE THREAD

**Issue by akashAD98** [mikel-brostrom/Yolov7_StrongSORT_OSNet#42]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

i saw there is same issue in github issue, but still this isssue is not solved,im running it on google collab, code working firne for cpu but not on gpu-cuda @mikel-brostrom 

### Environment

google collab

**Comment by TaplierShiru** [comment]
Hi!
Face same issue here, it seems that there is an error in yolo7 (`dataset.py`) and in the `track.py` scripts. I suggest pull request for each repo to fix it, after them repo work properly.
For anyone as temporal solution I have [Colab](https://colab.research.google.com/drive/1tLsh-JGLlrQv-blXlrwAGZbPttY_uJmp?usp=sharing) where repo is cloned from my profile, and all seems work as intended.

**Comment by mikel-brostrom** [comment]
I have updated the repo with your PRs @TaplierShiru. Could you pleas double check that this is solved now?

**Comment by TaplierShiru** [comment]
> I have updated the repo with your PRs @TaplierShiru. Could you pleas double check that this is solved now?

Checked current work of the repo - all seems good, so I think this issue is resolved.
