### ISSUE TITLE
support for yolov7.onnx .engineor .xml file & reid .onnx file for doing inference,same features like yolov8_tracker

### ISSUE THREAD

**Issue by akashAD98** [mikel-brostrom/Yolov7_StrongSORT_OSNet#44]
### Search before asking

- [X] I have searched the YOLOv7 [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar enhancement requests.

### Description

i saw your https://github.com/mikel-brostrom/yolov8_tracking repo, here you have provided different model support, so its possible for you to reflect same features for yolov7 model?

### Use case

want to load the model on cpu so im looking for.xml versions of both detection & tracker weight

**Comment by mikel-brostrom** [comment]
The easiest thing to do here is just to copy paste the export file from https://github.com/mikel-brostrom/yolov8_tracking into this repo. I don't have any plans of maintaining this repo more than the bare minimum, I don't have time for both. 99% percent of my time on github is spent there. This was a small detour :smile: . But feel free to submit a PR

**Comment by akashAD98** [comment]
@mikel-brostrom i tried this way, & thank you so much for your work & time, really appriciated your work

1. cloned yolov7 repo ,& converted yolov7.pt to yolov7.onnx
```
!python export.py --weights yolov7-tiny.pt --grid --end2end --simplify \
        --topk-all 100 --iou-thres 0.65 --conf-thres 0.35 --img-size 640 640 --max-wh 640
```

& tried 
```
!python track.py --yolo-weights /content/yolov7/yolov7-tiny.onnx --strong-sort-weights osnet_x0_25_msmt17.pt --source out.avi --save-vid --conf-thres 0.15 --device 0
```
im getting this error,seems yolov7 export.py not supporting

<img width="672" alt="image" src="https://user-images.githubusercontent.com/62583018/220416366-27b3baa1-e5d8-438b-ac0b-da23099327bc.png">


2. i used your repo  export.py  code, its also not working ,

https://github.com/mikel-brostrom/yolov7/blob/3ab80fb707528cdc0aaad8e7cef39546a1ccc7f2/export.py


3. as per your instruction copy the code of yolov8_tracker -export.py(this code is from yolov5) ,i tried it but I'm getting layers not found  error


i guess direct copy-pasting will not work here. right, apart from this i need to do few chnges?? bcz yolov7 & yolov8 weights are different & having diff layer


sorry I'm not that expert in coding, how can I fix this issue, I want to use yolov7.onnx & reid.onnx weight for object tracking  inference.

**Comment by mikel-brostrom** [comment]
Sorry cannot help you out with Yolov7 export stuff as I am not the creator of that repo

**Comment by akashAD98** [comment]
@mikel-brostromokay no problem, im getting issues with yolov7 .onnx file format, anyway thanks for your kind reply :)

**Comment by akashAD98** [comment]
@mikel-brostrom i have implemented object detection code for yolov7 , you can add .onnx,.xml file & apply tracker on it, i have been trying with deep sort, if you want to implement it with others tracker then ill share my code with you
