### ISSUE TITLE
No module named 'torchreid.metrics'

### ISSUE THREAD

**Issue by OOHAN-zxy** [mikel-brostrom/Yolov7_StrongSORT_OSNet#46]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Yolov7_StrongSORT_OSNet Component

Tracking

### Bug

I have done the following:
pip install torchreid.
But  the problem still occurred:

C:\python\anzhuang\envs\zxy\python.exe F:/OOHAN/ZhuXY-Projects/MOT/Yolov7_StrongSORT_OSNet-mikel-brostrom/strong_sort/sort/nn_matching.py
C:\python\anzhuang\envs\zxy\lib\site-packages\torchreid\reid\metrics\rank.py:12: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  'Cython evaluation (very fast so highly recommended) is '
Traceback (most recent call last):
  File "F:/OOHAN/ZhuXY-Projects/MOT/Yolov7_StrongSORT_OSNet-mikel-brostrom/strong_sort/sort/nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid.metrics'

### Environment

I am using anaconda environment with all requirements. What could be the issue?

### Minimal Reproducible Example

from torchreid.metrics.distance import compute_distance_matrix

**Comment by shijiancode** [comment]
Hello, how did you solve this problem
