### ISSUE TITLE
This project does not support multi-camera

### ISSUE THREAD

**Issue by dranhclub** [mikel-brostrom/Yolov7_StrongSORT_OSNet#48]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Why do you mention "multiple-camera" in project description while this project does not support multi-camera at all?
> Real-time multi-camera multi-object tracker using YOLOv7 and StrongSORT with OSNet

**Comment by mikel-brostrom** [comment]
It supports non-overlapping cameras

**Comment by mikel-brostrom** [comment]
It is impossible to provide an overlapping multi-camera off-the-box setup. Given that you need all the calibration matrices. I cannot do that for you

**Comment by shijiancode** [comment]
Can this code achieve the same ID for the same person under different cameras

**Comment by shijiancode** [comment]
> It is impossible to provide an overlapping multi-camera off-the-box setup. Given that you need all the calibration matrices. I cannot do that for you

Can this code achieve the same ID for the same person under different cameras
