### ISSUE TITLE
Unable to find module/folder despite being in the directory YOLOV7 and YOLOV5

### ISSUE THREAD

**Issue by C0NGTRI123** [mikel-brostrom/Yolov7_StrongSORT_OSNet#5]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I run tracking Yolov5 + StrongSort and Yolov7 + StrongSort and they have structure:

```
> yolov5
> yolov7
> strongsort
main.py
```
And I connect them with the code in the main.py like this:
```
FILE = Path(__file__).resolve()
ROOT = FILE.parents[0]  # yolov5 strongsort root directory
WEIGHTS = ROOT / 'weights'

if str(ROOT) not in sys.path:
    sys.path.append(str(ROOT))  # add ROOT to PATH
if str(ROOT / 'yolov5') not in sys.path:
    sys.path.append(str(ROOT / 'yolov5'))  # add yolov7 ROOT to PATH
if str(ROOT / 'yolov7') not in sys.path:
    sys.path.append(str(ROOT / 'yolov7'))  # add yolov7 ROOT to PATH
if str(ROOT / 'strong_sort') not in sys.path:
    sys.path.append(str(ROOT / 'strong_sort'))  # add strong_sort ROOT to PATH
ROOT = Path(os.path.relpath(ROOT, Path.cwd()))  # relative
```
When i take model from yolov7 like this:
```
model = attempt_load('model/yolov7.pt', map_location=torch.device('cpu'))
print(model)
```
They have error
 ```ModuleNotFoundError: No module named 'utils.google_utils'```. I understand they use attempt_load in yolov5 and not use yolov7. Help me about this problem

**Comment by mikel-brostrom** [comment]
yolov5 and yolov7 contain modules with the same name, hence they will overwrite each other. That is why I chose to have them in separate repos
