### ISSUE TITLE
Can this project realise multi camera multi person tracking with ReID?

### ISSUE THREAD

**Issue by JDmoric** [mikel-brostrom/Yolov7_StrongSORT_OSNet#50]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Can this project realise multi camera multi person tracking with ReID?

**Comment by rlekey** [comment]
check https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues/10
