### ISSUE TITLE
Run with two camera

### ISSUE THREAD

**Issue by JDmoric** [mikel-brostrom/Yolov7_StrongSORT_OSNet#51]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Hi,
What a wonderful work! But I want to know how to run with two camera in the same time?

**Comment by Xlp711** [comment]
I have the same question here. 

I am wondering how can I track two cameras from different angles to improve the accuracy.

**Comment by rlekey** [comment]
check https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues/10
