### ISSUE TITLE
Can I track directly using a separately trained V7 model? Do I need to retrain my StrongSORT model?

### ISSUE THREAD

**Issue by Garvise** [mikel-brostrom/Yolov7_StrongSORT_OSNet#53]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Can I track directly using a separately trained V7 model? Do I need to retrain my StrongSORT model?

**Comment by mikel-brostrom** [comment]
> Can I track directly using a separately trained V7 model?

Yolov7 is not officially supported but should be relatively easy to add here: https://github.com/mikel-brostrom/yolo_tracking/blob/master/examples/multi_yolo_backend.py. Just add inference and postprocess.

> Do I need to retrain my StrongSORT model?

Ideally yes, if you have a custom ReID datasets. But I recommend you to start with the ReID models offered in this repo.
