### ISSUE TITLE
ModuleNotFoundError: No module named 'torchreid'

### ISSUE THREAD

**Issue by dsnsabari** [mikel-brostrom/Yolov7_StrongSORT_OSNet#55]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and [discussions](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/discussions) and found no similar questions.

### Bug

  File "D:\Person_Tracking\Yolov7_StrongSORT_OSNet-main\strong_sort\sort\nn_matching.py", line 6, in <module>
    from torchreid.metrics.distance import compute_distance_matrix
ModuleNotFoundError: No module named 'torchreid'

### Environment

- Yolo7 = yolov7.pt
- strong-sort-weights = osnet_x1_0_imagenet.pth
- OS: windows10
- 

### Minimal Reproducible Example

```
python track.py --source D:/Person_Tracking/2_person/GTVideos/3746_20220113_fm24745l_20220109125210_20220109125225/*.jpg  --yolo-weights D:/Person_Tracking/Yolov7_StrongSORT_OSNet-main/yolov7.pt --strong-sort-weights D:/Person_Tracking/Yolov7_StrongSORT_OSNet-main/osnet_x1_0_imagenet.pth
```

**Comment by dsnsabari** [comment]
@mikel-brostrom , I am getting the below error. But when i downloaded the pre-trained os_net. it is available only in ".pth" format. What should i do? 


Could you share the osnet model in .pt format? 

AssertionError: D:/Person_Tracking/Yolov7_StrongSORT_OSNet-main/osnet_x1_0_imagenet.pth acceptable suffix is ['.pt', '.torchscript', '.onnx', '_openvino_model', '.engine', '.mlmodel', '_saved_model', '.pb', '.tflite', '_edgetpu.tflite', '_web_model', '.xml']

**Comment by MJ-06** [comment]
hi @dsnsabari, for torch reid download this repository: https://github.com/KaiyangZhou/deep-person-reid
and then move the torchreid folder to the proper directory
you will have to install the requirements, setup of reid is not necessary.

And for os_net.pth models try renaming the .pth model to .pt it should work
