### ISSUE TITLE
Multi-Camera-Multi-Object-Detection with Re-Identification

### ISSUE THREAD

**Issue by muhammad-usama-aleem** [mikel-brostrom/Yolov7_StrongSORT_OSNet#58]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I looked at the several related issues before opening a new issue, but most of the same question were un-answered.

My question is same as [issue# 25](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues/25)

how can we track the same person person with different cameras? For example, if a person is detected by a camera, then this person is labeled with an id number, then this person can keep this id number to the other camera.

@mikel-brostrom ,Please let us know if it's yet implemented or not. Thanks for your effort.

**Comment by joaorulff** [comment]
I have the same question. Will it be answered?
