### ISSUE TITLE
How to Use yolov7-mask.pt to Also Include Instance Segmentations?

### ISSUE THREAD

**Issue by Marx-Melencio** [mikel-brostrom/Yolov7_StrongSORT_OSNet#6]
First of all, thanks for the helpful repo!

I'd greatly appreciate any guidance on how to use the pretrained yolov7-mask.pt model (available in YOLOv7 repo) to also include segmentations for each detected object.

Thanks in advance!

**Comment by mikel-brostrom** [comment]
StrongSORT is design for tracking based on bboxes, segmentation can be ploted separatley
