### ISSUE TITLE
how to replace the strong_sort_weight?

### ISSUE THREAD

**Issue by sssssshf** [mikel-brostrom/Yolov7_StrongSORT_OSNet#8]
### Search before asking

- [X] I have searched the Yolov7_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov7_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Thank you for your work and contribution.
Itrained a new light model (osnet),How to replace the strong_sort_weight.

**Comment by mikel-brostrom** [comment]
`python track.py --strong-sort-weights /path/to/your/osnet_x0_25_model.pt`
